name: Refresh Hytale downloader credentials

on:
  schedule:
    # Run automatically every 2 weeks
    - cron: 0 0 */14 * *

  # Can also trigger this manually.
  workflow_dispatch:

concurrency:
  # The same group as build.yml
  group: secret-writer

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Renew refresh token
        env:
          HYTALE_DOWNLOADER_CREDENTIALS: ${{ secrets.HYTALE_DOWNLOADER_CREDENTIALS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

        run: |
          gh secret list > /dev/null
  
          printf %s "$HYTALE_DOWNLOADER_CREDENTIALS" | base64 -d > .hytale-downloader-credentials.json
          wget 'https://downloader.hytale.com/hytale-downloader.zip' -O downloader.zip
          unzip downloader.zip
          chmod +x hytale-downloader-linux-amd64
  
          set +e
          ./hytale-downloader-linux-amd64 -skip-update-check -print-version > version
          exit_code=$?
          set -e
  
          base64 -w 0 .hytale-downloader-credentials.json | gh secret set HYTALE_DOWNLOADER_CREDENTIALS
          exit "$exit_code"